// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { paths } from "@octokit-next/types-openapi-ghec-diff-to-api.github.com";
import { Simplify } from "type-fest";

import "@octokit-next/types-rest-api";

export type ResponseHeadersDiff = {
  "x-github-enterprise-version": string;
};

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["github.com"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = {
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/orgs#remove-a-saml-sso-authorization-for-an-organization
   */
  "DELETE /orgs/{org}/credential-authorizations/{credential_id}": Operation<
    paths,
    "delete",
    "/orgs/{org}/credential-authorizations/{credential_id}"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#unlink-external-idp-group-team-connection
   */
  "DELETE /orgs/{org}/teams/{team_slug}/external-groups": Operation<
    paths,
    "delete",
    "/orgs/{org}/teams/{team_slug}/external-groups"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#delete-a-scim-user-from-an-organization
   */
  "DELETE /scim/v2/organizations/{org}/Users/{scim_user_id}": Operation<
    paths,
    "delete",
    "/scim/v2/organizations/{org}/Users/{scim_user_id}"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/enterprise-admin#get-the-audit-log-for-an-enterprise
   */
  "GET /enterprises/{enterprise}/audit-log": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/audit-log"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/enterprise-admin#list-enterprise-consumed-licenses
   */
  "GET /enterprises/{enterprise}/consumed-licenses": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/consumed-licenses"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/enterprise-admin#get-a-license-sync-status
   */
  "GET /enterprises/{enterprise}/license-sync-status": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/license-sync-status"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/billing#get-github-actions-billing-for-an-enterprise
   */
  "GET /enterprises/{enterprise}/settings/billing/actions": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/settings/billing/actions"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/billing#get-github-packages-billing-for-an-enterprise
   */
  "GET /enterprises/{enterprise}/settings/billing/packages": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/settings/billing/packages"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/billing#get-shared-storage-billing-for-an-enterprise
   */
  "GET /enterprises/{enterprise}/settings/billing/shared-storage": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/settings/billing/shared-storage"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/actions/oidc#get-the-customization-template-for-an-oidc-subject-claim-for-an-organization
   */
  "GET /orgs/{org}/actions/oidc/customization/sub": Operation<
    paths,
    "get",
    "/orgs/{org}/actions/oidc/customization/sub"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/orgs#get-audit-log
   */
  "GET /orgs/{org}/audit-log": Operation<paths, "get", "/orgs/{org}/audit-log">;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/orgs#list-saml-sso-authorizations-for-an-organization
   */
  "GET /orgs/{org}/credential-authorizations": Operation<
    paths,
    "get",
    "/orgs/{org}/credential-authorizations"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#external-idp-group-info-for-an-organization
   */
  "GET /orgs/{org}/external-group/{group_id}": Operation<
    paths,
    "get",
    "/orgs/{org}/external-group/{group_id}"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#list-external-idp-groups-for-an-organization
   */
  "GET /orgs/{org}/external-groups": Operation<
    paths,
    "get",
    "/orgs/{org}/external-groups"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#list-idp-groups-for-an-organization
   */
  "GET /orgs/{org}/team-sync/groups": Operation<
    paths,
    "get",
    "/orgs/{org}/team-sync/groups"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#list-external-idp-group-team-connection
   */
  "GET /orgs/{org}/teams/{team_slug}/external-groups": Operation<
    paths,
    "get",
    "/orgs/{org}/teams/{team_slug}/external-groups"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#list-idp-groups-for-a-team
   */
  "GET /orgs/{org}/teams/{team_slug}/team-sync/group-mappings": Operation<
    paths,
    "get",
    "/orgs/{org}/teams/{team_slug}/team-sync/group-mappings"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/actions/oidc#get-the-opt-out-flag-of-an-oidc-subject-claim-customization-for-a-repository
   */
  "GET /repos/{owner}/{repo}/actions/oidc/customization/sub": Operation<
    paths,
    "get",
    "/repos/{owner}/{repo}/actions/oidc/customization/sub"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#list-scim-provisioned-identities
   */
  "GET /scim/v2/organizations/{org}/Users": Operation<
    paths,
    "get",
    "/scim/v2/organizations/{org}/Users"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#get-scim-provisioning-information-for-a-user
   */
  "GET /scim/v2/organizations/{org}/Users/{scim_user_id}": Operation<
    paths,
    "get",
    "/scim/v2/organizations/{org}/Users/{scim_user_id}"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#list-idp-groups-for-a-team-legacy
   */
  "GET /teams/{team_id}/team-sync/group-mappings": Operation<
    paths,
    "get",
    "/teams/{team_id}/team-sync/group-mappings"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#link-external-idp-group-team-connection
   */
  "PATCH /orgs/{org}/teams/{team_slug}/external-groups": Operation<
    paths,
    "patch",
    "/orgs/{org}/teams/{team_slug}/external-groups"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#create-or-update-idp-group-connections
   */
  "PATCH /orgs/{org}/teams/{team_slug}/team-sync/group-mappings": Operation<
    paths,
    "patch",
    "/orgs/{org}/teams/{team_slug}/team-sync/group-mappings"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#update-an-attribute-for-a-scim-user
   */
  "PATCH /scim/v2/organizations/{org}/Users/{scim_user_id}": Operation<
    paths,
    "patch",
    "/scim/v2/organizations/{org}/Users/{scim_user_id}"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/teams#create-or-update-idp-group-connections-legacy
   */
  "PATCH /teams/{team_id}/team-sync/group-mappings": Operation<
    paths,
    "patch",
    "/teams/{team_id}/team-sync/group-mappings"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#provision-and-invite-a-scim-user
   */
  "POST /scim/v2/organizations/{org}/Users": Operation<
    paths,
    "post",
    "/scim/v2/organizations/{org}/Users"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/actions/oidc#set-actions-oidc-custom-issuer-policy-for-enterprise
   */
  "PUT /enterprises/{enterprise}/actions/oidc/customization/issuer": Operation<
    paths,
    "put",
    "/enterprises/{enterprise}/actions/oidc/customization/issuer"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/actions/oidc#set-the-customization-template-for-an-oidc-subject-claim-for-an-organization
   */
  "PUT /orgs/{org}/actions/oidc/customization/sub": Operation<
    paths,
    "put",
    "/orgs/{org}/actions/oidc/customization/sub"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/actions/oidc#set-the-opt-out-flag-of-an-oidc-subject-claim-customization-for-a-repository
   */
  "PUT /repos/{owner}/{repo}/actions/oidc/customization/sub": Operation<
    paths,
    "put",
    "/repos/{owner}/{repo}/actions/oidc/customization/sub"
  >;
  /**
   * @see https://docs.github.com/enterprise-cloud@latest//rest/reference/scim#set-scim-information-for-a-provisioned-user
   */
  "PUT /scim/v2/organizations/{org}/Users/{scim_user_id}": Operation<
    paths,
    "put",
    "/scim/v2/organizations/{org}/Users/{scim_user_id}"
  >;
};

export type RemovedRoutes = never;

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      ghec: {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["github.com"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["github.com"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["ghec"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
