// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { paths } from "@octokit-next/types-openapi-github.ae-diff-to-api.github.com";
import { Simplify } from "type-fest";

import "@octokit-next/types-rest-api";

export type ResponseHeadersDiff = {
  "x-github-enterprise-version": string;
};

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["github.com"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = {
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-a-global-webhook
   */
  "DELETE /admin/hooks/{hook_id}": Operation<
    paths,
    "delete",
    "/admin/hooks/{hook_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-a-public-key
   */
  "DELETE /admin/keys/{key_ids}": Operation<
    paths,
    "delete",
    "/admin/keys/{key_ids}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-a-pre-receive-environment
   */
  "DELETE /admin/pre-receive-environments/{pre_receive_environment_id}": Operation<
    paths,
    "delete",
    "/admin/pre-receive-environments/{pre_receive_environment_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-a-personal-access-token
   */
  "DELETE /admin/tokens/{token_id}": Operation<
    paths,
    "delete",
    "/admin/tokens/{token_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-a-user
   */
  "DELETE /admin/users/{username}": Operation<
    paths,
    "delete",
    "/admin/users/{username}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#delete-an-impersonation-oauth-token
   */
  "DELETE /admin/users/{username}/authorizations": Operation<
    paths,
    "delete",
    "/admin/users/{username}/authorizations"
  >;
  /**
   * @see
   */
  "DELETE /enterprise/announcement": Operation<
    paths,
    "delete",
    "/enterprise/announcement"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/teams#unlink-external-idp-group-team-connection
   */
  "DELETE /orgs/{org}/teams/{team_slug}/external-groups": Operation<
    paths,
    "delete",
    "/orgs/{org}/teams/{team_slug}/external-groups"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#unsuspend-a-user
   */
  "DELETE /users/{username}/suspended": Operation<
    paths,
    "delete",
    "/users/{username}/suspended"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#list-global-webhooks
   */
  "GET /admin/hooks": Operation<paths, "get", "/admin/hooks">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-a-global-webhook
   */
  "GET /admin/hooks/{hook_id}": Operation<
    paths,
    "get",
    "/admin/hooks/{hook_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#list-public-keys
   */
  "GET /admin/keys": Operation<paths, "get", "/admin/keys">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#list-pre-receive-environments
   */
  "GET /admin/pre-receive-environments": Operation<
    paths,
    "get",
    "/admin/pre-receive-environments"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-a-pre-receive-environment
   */
  "GET /admin/pre-receive-environments/{pre_receive_environment_id}": Operation<
    paths,
    "get",
    "/admin/pre-receive-environments/{pre_receive_environment_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-the-download-status-for-a-pre-receive-environment
   */
  "GET /admin/pre-receive-environments/{pre_receive_environment_id}/downloads/latest": Operation<
    paths,
    "get",
    "/admin/pre-receive-environments/{pre_receive_environment_id}/downloads/latest"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#list-personal-access-tokens
   */
  "GET /admin/tokens": Operation<paths, "get", "/admin/tokens">;
  /**
   * @see
   */
  "GET /enterprise/announcement": Operation<
    paths,
    "get",
    "/enterprise/announcement"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-license-information
   */
  "GET /enterprise/settings/license": Operation<
    paths,
    "get",
    "/enterprise/settings/license"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-statistics
   */
  "GET /enterprise/stats/all": Operation<paths, "get", "/enterprise/stats/all">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-comment-statistics
   */
  "GET /enterprise/stats/comments": Operation<
    paths,
    "get",
    "/enterprise/stats/comments"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-gist-statistics
   */
  "GET /enterprise/stats/gists": Operation<
    paths,
    "get",
    "/enterprise/stats/gists"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-hooks-statistics
   */
  "GET /enterprise/stats/hooks": Operation<
    paths,
    "get",
    "/enterprise/stats/hooks"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-issues-statistics
   */
  "GET /enterprise/stats/issues": Operation<
    paths,
    "get",
    "/enterprise/stats/issues"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-milestone-statistics
   */
  "GET /enterprise/stats/milestones": Operation<
    paths,
    "get",
    "/enterprise/stats/milestones"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-organization-statistics
   */
  "GET /enterprise/stats/orgs": Operation<
    paths,
    "get",
    "/enterprise/stats/orgs"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-pages-statistics
   */
  "GET /enterprise/stats/pages": Operation<
    paths,
    "get",
    "/enterprise/stats/pages"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-pull-requests-statistics
   */
  "GET /enterprise/stats/pulls": Operation<
    paths,
    "get",
    "/enterprise/stats/pulls"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-repository-statistics
   */
  "GET /enterprise/stats/repos": Operation<
    paths,
    "get",
    "/enterprise/stats/repos"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-users-statistics
   */
  "GET /enterprise/stats/users": Operation<
    paths,
    "get",
    "/enterprise/stats/users"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#get-the-audit-log-for-an-enterprise
   */
  "GET /enterprises/{enterprise}/audit-log": Operation<
    paths,
    "get",
    "/enterprises/{enterprise}/audit-log"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/orgs#get-audit-log
   */
  "GET /orgs/{org}/audit-log": Operation<paths, "get", "/orgs/{org}/audit-log">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/teams#external-idp-group-info-for-an-organization
   */
  "GET /orgs/{org}/external-group/{group_id}": Operation<
    paths,
    "get",
    "/orgs/{org}/external-group/{group_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/teams#list-external-idp-groups-for-an-organization
   */
  "GET /orgs/{org}/external-groups": Operation<
    paths,
    "get",
    "/orgs/{org}/external-groups"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#update-a-global-webhook
   */
  "PATCH /admin/hooks/{hook_id}": Operation<
    paths,
    "patch",
    "/admin/hooks/{hook_id}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#update-an-organization-name
   */
  "PATCH /admin/organizations/{org}": Operation<
    paths,
    "patch",
    "/admin/organizations/{org}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#update-a-pre-receive-environment
   */
  "PATCH /admin/pre-receive-environments/{pre_receive_environment_id}": Operation<
    paths,
    "patch",
    "/admin/pre-receive-environments/{pre_receive_environment_id}"
  >;
  /**
   * @see
   */
  "PATCH /enterprise/announcement": Operation<
    paths,
    "patch",
    "/enterprise/announcement"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/teams#link-external-idp-group-team-connection
   */
  "PATCH /orgs/{org}/teams/{team_slug}/external-groups": Operation<
    paths,
    "patch",
    "/orgs/{org}/teams/{team_slug}/external-groups"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#create-a-global-webhook
   */
  "POST /admin/hooks": Operation<paths, "post", "/admin/hooks">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#ping-a-global-webhook
   */
  "POST /admin/hooks/{hook_id}/pings": Operation<
    paths,
    "post",
    "/admin/hooks/{hook_id}/pings"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#create-an-organization
   */
  "POST /admin/organizations": Operation<paths, "post", "/admin/organizations">;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#create-a-pre-receive-environment
   */
  "POST /admin/pre-receive-environments": Operation<
    paths,
    "post",
    "/admin/pre-receive-environments"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#start-a-pre-receive-environment-download
   */
  "POST /admin/pre-receive-environments/{pre_receive_environment_id}/downloads": Operation<
    paths,
    "post",
    "/admin/pre-receive-environments/{pre_receive_environment_id}/downloads"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#create-an-impersonation-oauth-token
   */
  "POST /admin/users/{username}/authorizations": Operation<
    paths,
    "post",
    "/admin/users/{username}/authorizations"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/apps#reset-an-authorization
   */
  "POST /applications/{client_id}/tokens/{access_token}": Operation<
    paths,
    "post",
    "/applications/{client_id}/tokens/{access_token}"
  >;
  /**
   * @see https://docs.github.com/github-ae@latest/rest/reference/enterprise-admin#suspend-a-user
   */
  "PUT /users/{username}/suspended": Operation<
    paths,
    "put",
    "/users/{username}/suspended"
  >;
};

export type RemovedRoutes =
  | never
  | "DELETE /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations/{org_id}"
  | "DELETE /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "DELETE /enterprises/{enterprise}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /organizations/{org}/codespaces/secrets/{secret_name}"
  | "DELETE /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}"
  | "DELETE /orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}"
  | "DELETE /orgs/{org}/actions/runners/{runner_id}/labels"
  | "DELETE /orgs/{org}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /orgs/{org}/blocks/{username}"
  | "DELETE /orgs/{org}/custom_roles/{role_id}"
  | "DELETE /orgs/{org}/dependabot/secrets/{secret_name}"
  | "DELETE /orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}"
  | "DELETE /orgs/{org}/interaction-limits"
  | "DELETE /orgs/{org}/invitations/{invitation_id}"
  | "DELETE /orgs/{org}/members/{username}/codespaces/{codespace_name}"
  | "DELETE /orgs/{org}/migrations/{migration_id}/archive"
  | "DELETE /orgs/{org}/migrations/{migration_id}/repos/{repo_name}/lock"
  | "DELETE /orgs/{org}/packages/{package_type}/{package_name}"
  | "DELETE /orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "DELETE /orgs/{org}/public_members/{username}"
  | "DELETE /orgs/{org}/security-managers/teams/{team_slug}"
  | "DELETE /repos/{owner}/{repo}/actions/caches"
  | "DELETE /repos/{owner}/{repo}/actions/caches/{cache_id}"
  | "DELETE /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "DELETE /repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /repos/{owner}/{repo}/automated-security-fixes"
  | "DELETE /repos/{owner}/{repo}/codespaces/secrets/{secret_name}"
  | "DELETE /repos/{owner}/{repo}/dependabot/secrets/{secret_name}"
  | "DELETE /repos/{owner}/{repo}/import"
  | "DELETE /repos/{owner}/{repo}/interaction-limits"
  | "DELETE /repos/{owner}/{repo}/tags/protection/{tag_protection_id}"
  | "DELETE /repos/{owner}/{repo}/vulnerability-alerts"
  | "DELETE /repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}"
  | "DELETE /user/blocks/{username}"
  | "DELETE /user/codespaces/secrets/{secret_name}"
  | "DELETE /user/codespaces/secrets/{secret_name}/repositories/{repository_id}"
  | "DELETE /user/codespaces/{codespace_name}"
  | "DELETE /user/emails"
  | "DELETE /user/interaction-limits"
  | "DELETE /user/migrations/{migration_id}/repos/{repo_name}/lock"
  | "DELETE /user/packages/{package_type}/{package_name}"
  | "DELETE /user/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "DELETE /user/ssh_signing_keys/{ssh_signing_key_id}"
  | "DELETE /users/{username}/packages/{package_type}/{package_name}"
  | "DELETE /users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "GET /enterprise-installation/{enterprise_or_org}/server-statistics"
  | "GET /enterprises/{enterprise}/actions/cache/usage"
  | "GET /enterprises/{enterprise}/actions/permissions/workflow"
  | "GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations"
  | "GET /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "GET /enterprises/{enterprise}/code-scanning/alerts"
  | "GET /enterprises/{enterprise}/secret-scanning/alerts"
  | "GET /enterprises/{enterprise}/settings/billing/advanced-security"
  | "GET /events"
  | "GET /marketplace_listing/accounts/{account_id}"
  | "GET /marketplace_listing/plans"
  | "GET /marketplace_listing/plans/{plan_id}/accounts"
  | "GET /marketplace_listing/stubbed/accounts/{account_id}"
  | "GET /marketplace_listing/stubbed/plans"
  | "GET /marketplace_listing/stubbed/plans/{plan_id}/accounts"
  | "GET /networks/{owner}/{repo}/events"
  | "GET /organizations/{organization_id}/custom_roles"
  | "GET /organizations/{org}/codespaces/secrets"
  | "GET /organizations/{org}/codespaces/secrets/public-key"
  | "GET /organizations/{org}/codespaces/secrets/{secret_name}"
  | "GET /organizations/{org}/codespaces/secrets/{secret_name}/repositories"
  | "GET /orgs/{org}/actions/cache/usage"
  | "GET /orgs/{org}/actions/cache/usage-by-repository"
  | "GET /orgs/{org}/actions/permissions/workflow"
  | "GET /orgs/{org}/actions/runner-groups/{runner_group_id}/repositories"
  | "GET /orgs/{org}/actions/runner-groups/{runner_group_id}/runners"
  | "GET /orgs/{org}/actions/runners/{runner_id}/labels"
  | "GET /orgs/{org}/blocks"
  | "GET /orgs/{org}/blocks/{username}"
  | "GET /orgs/{org}/code-scanning/alerts"
  | "GET /orgs/{org}/codespaces"
  | "GET /orgs/{org}/dependabot/secrets"
  | "GET /orgs/{org}/dependabot/secrets/public-key"
  | "GET /orgs/{org}/dependabot/secrets/{secret_name}"
  | "GET /orgs/{org}/dependabot/secrets/{secret_name}/repositories"
  | "GET /orgs/{org}/events"
  | "GET /orgs/{org}/failed_invitations"
  | "GET /orgs/{org}/fine_grained_permissions"
  | "GET /orgs/{org}/interaction-limits"
  | "GET /orgs/{org}/invitations"
  | "GET /orgs/{org}/invitations/{invitation_id}/teams"
  | "GET /orgs/{org}/migrations/{migration_id}/archive"
  | "GET /orgs/{org}/migrations/{migration_id}/repositories"
  | "GET /orgs/{org}/packages"
  | "GET /orgs/{org}/packages/{package_type}/{package_name}"
  | "GET /orgs/{org}/packages/{package_type}/{package_name}/versions"
  | "GET /orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "GET /orgs/{org}/public_members"
  | "GET /orgs/{org}/public_members/{username}"
  | "GET /orgs/{org}/secret-scanning/alerts"
  | "GET /orgs/{org}/security-managers"
  | "GET /orgs/{org}/settings/billing/actions"
  | "GET /orgs/{org}/settings/billing/advanced-security"
  | "GET /orgs/{org}/settings/billing/packages"
  | "GET /orgs/{org}/settings/billing/shared-storage"
  | "GET /orgs/{org}/teams/{team_slug}/invitations"
  | "GET /repos/{owner}/{repo}/actions/cache/usage"
  | "GET /repos/{owner}/{repo}/actions/caches"
  | "GET /repos/{owner}/{repo}/actions/permissions/access"
  | "GET /repos/{owner}/{repo}/actions/permissions/workflow"
  | "GET /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals"
  | "GET /repos/{owner}/{repo}/actions/runs/{run_id}/pending_deployments"
  | "GET /repos/{owner}/{repo}/code-scanning/codeql/databases"
  | "GET /repos/{owner}/{repo}/code-scanning/codeql/databases/{language}"
  | "GET /repos/{owner}/{repo}/codespaces"
  | "GET /repos/{owner}/{repo}/codespaces/devcontainers"
  | "GET /repos/{owner}/{repo}/codespaces/machines"
  | "GET /repos/{owner}/{repo}/codespaces/new"
  | "GET /repos/{owner}/{repo}/codespaces/secrets"
  | "GET /repos/{owner}/{repo}/codespaces/secrets/public-key"
  | "GET /repos/{owner}/{repo}/codespaces/secrets/{secret_name}"
  | "GET /repos/{owner}/{repo}/community/profile"
  | "GET /repos/{owner}/{repo}/dependabot/alerts"
  | "GET /repos/{owner}/{repo}/dependabot/alerts/{alert_number}"
  | "GET /repos/{owner}/{repo}/dependabot/secrets"
  | "GET /repos/{owner}/{repo}/dependabot/secrets/public-key"
  | "GET /repos/{owner}/{repo}/dependabot/secrets/{secret_name}"
  | "GET /repos/{owner}/{repo}/dependency-graph/compare/{basehead}"
  | "GET /repos/{owner}/{repo}/import"
  | "GET /repos/{owner}/{repo}/import/authors"
  | "GET /repos/{owner}/{repo}/import/large_files"
  | "GET /repos/{owner}/{repo}/interaction-limits"
  | "GET /repos/{owner}/{repo}/pages/health"
  | "GET /repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations"
  | "GET /repos/{owner}/{repo}/tags/protection"
  | "GET /repos/{owner}/{repo}/traffic/clones"
  | "GET /repos/{owner}/{repo}/traffic/popular/paths"
  | "GET /repos/{owner}/{repo}/traffic/popular/referrers"
  | "GET /repos/{owner}/{repo}/traffic/views"
  | "GET /repos/{owner}/{repo}/vulnerability-alerts"
  | "GET /repositories"
  | "GET /repositories/{repository_id}/environments/{environment_name}/secrets"
  | "GET /repositories/{repository_id}/environments/{environment_name}/secrets/public-key"
  | "GET /repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}"
  | "GET /teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions"
  | "GET /teams/{team_id}/discussions/{discussion_number}/reactions"
  | "GET /teams/{team_id}/invitations"
  | "GET /user/blocks"
  | "GET /user/blocks/{username}"
  | "GET /user/codespaces"
  | "GET /user/codespaces/secrets"
  | "GET /user/codespaces/secrets/public-key"
  | "GET /user/codespaces/secrets/{secret_name}"
  | "GET /user/codespaces/secrets/{secret_name}/repositories"
  | "GET /user/codespaces/{codespace_name}"
  | "GET /user/codespaces/{codespace_name}/exports/{export_id}"
  | "GET /user/codespaces/{codespace_name}/machines"
  | "GET /user/emails"
  | "GET /user/interaction-limits"
  | "GET /user/marketplace_purchases"
  | "GET /user/marketplace_purchases/stubbed"
  | "GET /user/migrations/{migration_id}"
  | "GET /user/packages"
  | "GET /user/packages/{package_type}/{package_name}"
  | "GET /user/packages/{package_type}/{package_name}/versions"
  | "GET /user/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "GET /user/public_emails"
  | "GET /user/ssh_signing_keys"
  | "GET /user/ssh_signing_keys/{ssh_signing_key_id}"
  | "GET /users/{username}/events/public"
  | "GET /users/{username}/packages"
  | "GET /users/{username}/packages/{package_type}/{package_name}"
  | "GET /users/{username}/packages/{package_type}/{package_name}/versions"
  | "GET /users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}"
  | "GET /users/{username}/received_events"
  | "GET /users/{username}/received_events/public"
  | "GET /users/{username}/settings/billing/actions"
  | "GET /users/{username}/settings/billing/packages"
  | "GET /users/{username}/settings/billing/shared-storage"
  | "GET /users/{username}/ssh_signing_keys"
  | "PATCH /orgs/{org}/custom_roles/{role_id}"
  | "PATCH /repos/{owner}/{repo}/dependabot/alerts/{alert_number}"
  | "PATCH /repos/{owner}/{repo}/import"
  | "PATCH /repos/{owner}/{repo}/import/authors/{author_id}"
  | "PATCH /repos/{owner}/{repo}/import/lfs"
  | "PATCH /user/codespaces/{codespace_name}"
  | "PATCH /user/email/visibility"
  | "POST /applications/{client_id}/token/scoped"
  | "POST /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "POST /orgs/{org}/actions/runners/{runner_id}/labels"
  | "POST /orgs/{org}/custom_roles"
  | "POST /orgs/{org}/invitations"
  | "POST /orgs/{org}/members/{username}/codespaces/{codespace_name}/stop"
  | "POST /orgs/{org}/packages/{package_type}/{package_name}/restore"
  | "POST /orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore"
  | "POST /orgs/{org}/{security_product}/{enablement}"
  | "POST /repos/{owner}/{repo}/actions/jobs/{job_id}/rerun"
  | "POST /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "POST /repos/{owner}/{repo}/actions/runs/{run_id}/approve"
  | "POST /repos/{owner}/{repo}/actions/runs/{run_id}/pending_deployments"
  | "POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs"
  | "POST /repos/{owner}/{repo}/branches/{branch}/rename"
  | "POST /repos/{owner}/{repo}/codespaces"
  | "POST /repos/{owner}/{repo}/dependency-graph/snapshots"
  | "POST /repos/{owner}/{repo}/pages/deployment"
  | "POST /repos/{owner}/{repo}/pulls/{pull_number}/codespaces"
  | "POST /repos/{owner}/{repo}/releases/generate-notes"
  | "POST /repos/{owner}/{repo}/tags/protection"
  | "POST /teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions"
  | "POST /teams/{team_id}/discussions/{discussion_number}/reactions"
  | "POST /user/codespaces"
  | "POST /user/codespaces/{codespace_name}/exports"
  | "POST /user/codespaces/{codespace_name}/start"
  | "POST /user/codespaces/{codespace_name}/stop"
  | "POST /user/emails"
  | "POST /user/packages/{package_type}/{package_name}/restore"
  | "POST /user/packages/{package_type}/{package_name}/versions/{package_version_id}/restore"
  | "POST /user/ssh_signing_keys"
  | "POST /users/{username}/packages/{package_type}/{package_name}/restore"
  | "POST /users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore"
  | "PUT /enterprises/{enterprise}/actions/permissions/workflow"
  | "PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations"
  | "PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations/{org_id}"
  | "PUT /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "PUT /organizations/{org}/codespaces/secrets/{secret_name}"
  | "PUT /organizations/{org}/codespaces/secrets/{secret_name}/repositories"
  | "PUT /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}"
  | "PUT /orgs/{org}/actions/permissions/workflow"
  | "PUT /orgs/{org}/actions/runner-groups/{runner_group_id}/repositories"
  | "PUT /orgs/{org}/actions/runner-groups/{runner_group_id}/runners"
  | "PUT /orgs/{org}/actions/runners/{runner_id}/labels"
  | "PUT /orgs/{org}/blocks/{username}"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}/repositories"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}"
  | "PUT /orgs/{org}/interaction-limits"
  | "PUT /orgs/{org}/public_members/{username}"
  | "PUT /orgs/{org}/security-managers/teams/{team_slug}"
  | "PUT /repos/{owner}/{repo}/actions/permissions/access"
  | "PUT /repos/{owner}/{repo}/actions/permissions/workflow"
  | "PUT /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "PUT /repos/{owner}/{repo}/automated-security-fixes"
  | "PUT /repos/{owner}/{repo}/codespaces/secrets/{secret_name}"
  | "PUT /repos/{owner}/{repo}/dependabot/secrets/{secret_name}"
  | "PUT /repos/{owner}/{repo}/import"
  | "PUT /repos/{owner}/{repo}/interaction-limits"
  | "PUT /repos/{owner}/{repo}/vulnerability-alerts"
  | "PUT /repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}"
  | "PUT /user/blocks/{username}"
  | "PUT /user/codespaces/secrets/{secret_name}"
  | "PUT /user/codespaces/secrets/{secret_name}/repositories"
  | "PUT /user/codespaces/secrets/{secret_name}/repositories/{repository_id}"
  | "PUT /user/interaction-limits";

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "github.ae": {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["github.com"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["github.com"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["github.ae"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
