// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { paths } from "@octokit-next/types-openapi-ghes-3.3-diff-to-ghes-3.4";
import { Simplify } from "type-fest";

import {
  ResponseHeadersDiff as ImportResponseHeadersDiff,
  AddedEndpoints as ImportAddedEndpoints,
  RemovedRoutes as ImportRemovedRoutes,
} from "@octokit-next/types-rest-api-ghes-3.4";

export type ResponseHeadersDiff = ImportResponseHeadersDiff;

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["ghes-3.4"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = ImportAddedEndpoints & {
  /**
   * @see https://docs.github.com/enterprise-server@3.3/rest/reference/apps#revoke-a-grant-for-an-application
   */
  "DELETE /applications/{client_id}/grants/{access_token}": Operation<
    paths,
    "delete",
    "/applications/{client_id}/grants/{access_token}"
  >;
  /**
   * @see https://docs.github.com/enterprise-server@3.3/rest/reference/apps#revoke-an-authorization-for-an-application
   */
  "DELETE /applications/{client_id}/tokens/{access_token}": Operation<
    paths,
    "delete",
    "/applications/{client_id}/tokens/{access_token}"
  >;
  /**
   * @see https://docs.github.com/enterprise-server@3.3/rest/reference/apps#check-an-authorization
   */
  "GET /applications/{client_id}/tokens/{access_token}": Operation<
    paths,
    "get",
    "/applications/{client_id}/tokens/{access_token}"
  >;
  /**
   * @see https://docs.github.com/rest/reference/codes-of-conduct#get-the-code-of-conduct-for-a-repository
   */
  "GET /repos/{owner}/{repo}/community/code_of_conduct": Operation<
    paths,
    "get",
    "/repos/{owner}/{repo}/community/code_of_conduct",
    "scarlet-witch"
  >;
  /**
   * @see https://docs.github.com/enterprise-server@3.3/rest/reference/apps#reset-an-authorization
   */
  "POST /applications/{client_id}/tokens/{access_token}": Operation<
    paths,
    "post",
    "/applications/{client_id}/tokens/{access_token}"
  >;
  /**
   * @see https://docs.github.com/rest/reference/apps#create-a-content-attachment
   */
  "POST /content_references/{content_reference_id}/attachments": Operation<
    paths,
    "post",
    "/content_references/{content_reference_id}/attachments",
    "corsair"
  >;
  /**
   * @see https://docs.github.com/enterprise-server@3.3/rest/reference/apps#create-a-content-attachment
   */
  "POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments": Operation<
    paths,
    "post",
    "/repos/{owner}/{repo}/content_references/{content_reference_id}/attachments"
  >;
};

export type RemovedRoutes =
  | ImportRemovedRoutes
  | "DELETE /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "DELETE /enterprises/{enterprise}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /orgs/{org}/actions/runners/{runner_id}/labels"
  | "DELETE /orgs/{org}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /orgs/{org}/dependabot/secrets/{secret_name}"
  | "DELETE /orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}"
  | "DELETE /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "DELETE /repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}"
  | "DELETE /repos/{owner}/{repo}/dependabot/secrets/{secret_name}"
  | "GET /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "GET /enterprises/{enterprise}/secret-scanning/alerts"
  | "GET /enterprises/{enterprise}/settings/billing/advanced-security"
  | "GET /organizations/{organization_id}/custom_roles"
  | "GET /orgs/{org}/actions/runners/{runner_id}/labels"
  | "GET /orgs/{org}/dependabot/secrets"
  | "GET /orgs/{org}/dependabot/secrets/public-key"
  | "GET /orgs/{org}/dependabot/secrets/{secret_name}"
  | "GET /orgs/{org}/dependabot/secrets/{secret_name}/repositories"
  | "GET /orgs/{org}/migrations"
  | "GET /orgs/{org}/migrations/{migration_id}"
  | "GET /orgs/{org}/settings/billing/advanced-security"
  | "GET /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "GET /repos/{owner}/{repo}/dependabot/secrets"
  | "GET /repos/{owner}/{repo}/dependabot/secrets/public-key"
  | "GET /repos/{owner}/{repo}/dependabot/secrets/{secret_name}"
  | "GET /repos/{owner}/{repo}/replicas/caches"
  | "GET /user/migrations"
  | "GET /user/migrations/{migration_id}/archive"
  | "GET /user/migrations/{migration_id}/repositories"
  | "POST /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "POST /orgs/{org}/actions/runners/{runner_id}/labels"
  | "POST /orgs/{org}/migrations"
  | "POST /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "POST /user/migrations"
  | "PUT /enterprises/{enterprise}/actions/runners/{runner_id}/labels"
  | "PUT /orgs/{org}/actions/runners/{runner_id}/labels"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}/repositories"
  | "PUT /orgs/{org}/dependabot/secrets/{secret_name}/repositories/{repository_id}"
  | "PUT /repos/{owner}/{repo}/actions/runners/{runner_id}/labels"
  | "PUT /repos/{owner}/{repo}/dependabot/secrets/{secret_name}";

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "ghes-3.3": {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["ghes-3.4"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["ghes-3.4"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["ghes-3.3"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
