// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { Simplify } from "type-fest";

import {
  ResponseHeadersDiff as ImportResponseHeadersDiff,
  AddedEndpoints as ImportAddedEndpoints,
  RemovedRoutes as ImportRemovedRoutes,
} from "@octokit-next/types-rest-api-ghes-3.3";

export type ResponseHeadersDiff = ImportResponseHeadersDiff;

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["ghes-3.3"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = ImportAddedEndpoints & {};

export type RemovedRoutes =
  | ImportRemovedRoutes
  | "DELETE /repos/{owner}/{repo}/autolinks/{autolink_id}"
  | "DELETE /repos/{owner}/{repo}/lfs"
  | "GET /enterprises/{enterprise}/audit-log"
  | "GET /orgs/{org}/audit-log"
  | "GET /orgs/{org}/secret-scanning/alerts"
  | "GET /repos/{owner}/{repo}/autolinks"
  | "GET /repos/{owner}/{repo}/autolinks/{autolink_id}"
  | "GET /repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations"
  | "POST /repos/{owner}/{repo}/autolinks"
  | "POST /repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest"
  | "POST /repos/{owner}/{repo}/merge-upstream"
  | "POST /repos/{owner}/{repo}/releases/generate-notes"
  | "PUT /repos/{owner}/{repo}/lfs";

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "ghes-3.2": {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["ghes-3.3"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["ghes-3.3"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["ghes-3.2"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
