// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { paths } from "@octokit-next/types-openapi-ghes-3.0";
import { Simplify } from "type-fest";

import {
  ResponseHeadersDiff as ImportResponseHeadersDiff,
  EndpointsDiff as ImportEndpointsDiff,
} from "@octokit-next/types-rest-api-ghes-3.1";

export type ResponseHeadersDiff = ImportResponseHeadersDiff;

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["ghes-3.1"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type EndpointsDiff = ImportEndpointsDiff & {
  // ADDED endpoints

  // REMOVED endpoints

  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "DELETE /repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /orgs/{org}/audit-log": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /repos/{owner}/{repo}/secret-scanning/alerts": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "GET /repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}": never;
  /**
   * The endpoint exists for ghes-3.1 but does not exist for ghes-3.0
   */
  "POST /repos/{owner}/{repo}/branches/{branch}/rename": never;
};

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "ghes-3.0": {
        ResponseHeaders: Simplify<
          Octokit.ApiVersions["github.com"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["github.com"]["Endpoints"],
              keyof EndpointsDiff
            > &
              EndpointsDiff,
            Octokit.ApiVersions["ghes-3.0"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
