// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { Simplify } from "type-fest";

import {
  ResponseHeadersDiff as ImportResponseHeadersDiff,
  AddedEndpoints as ImportAddedEndpoints,
  RemovedRoutes as ImportRemovedRoutes,
} from "@octokit-next/types-rest-api-ghes-3.1";

export type ResponseHeadersDiff = ImportResponseHeadersDiff;

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["ghes-3.1"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = ImportAddedEndpoints & {};

export type RemovedRoutes =
  | ImportRemovedRoutes
  | "DELETE /repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}"
  | "GET /orgs/{org}/audit-log"
  | "GET /repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances"
  | "GET /repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}"
  | "GET /repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}"
  | "GET /repos/{owner}/{repo}/secret-scanning/alerts"
  | "GET /repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}"
  | "POST /repos/{owner}/{repo}/branches/{branch}/rename";

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "ghes-3.0": {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["ghes-3.1"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["ghes-3.1"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["ghes-3.0"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
