// DO NOT EDIT THIS FILE
import { Octokit } from "@octokit-next/types";
import { Operation, WithNewHeaders } from "@octokit-next/types-rest-api";
import { paths } from "@octokit-next/types-openapi-ghes-3.4-diff-to-ghes-3.5";
import { Simplify } from "type-fest";

import {
  ResponseHeadersDiff as ImportResponseHeadersDiff,
  AddedEndpoints as ImportAddedEndpoints,
  RemovedRoutes as ImportRemovedRoutes,
} from "@octokit-next/types-rest-api-ghes-3.5";

export type ResponseHeadersDiff = ImportResponseHeadersDiff;

export type ResponseHeaders = Simplify<
  Octokit.ApiVersions["ghes-3.5"]["ResponseHeaders"] & ResponseHeadersDiff
>;

export type AddedEndpoints = ImportAddedEndpoints & {
  /**
   * @see https://docs.github.com/enterprise-server@3.4/rest/reference/reactions/#delete-a-reaction-legacy
   */
  "DELETE /reactions/{reaction_id}": Operation<
    paths,
    "delete",
    "/reactions/{reaction_id}"
  >;
};

export type RemovedRoutes =
  | ImportRemovedRoutes
  | "DELETE /repos/{owner}/{repo}/tags/protection/{tag_protection_id}"
  | "GET /enterprises/{enterprise}/actions/cache/usage"
  | "GET /enterprises/{enterprise}/actions/cache/usage-policy"
  | "GET /orgs/{org}/actions/cache/usage"
  | "GET /orgs/{org}/actions/cache/usage-by-repository"
  | "GET /orgs/{org}/actions/permissions/workflow"
  | "GET /orgs/{org}/code-scanning/alerts"
  | "GET /repos/{owner}/{repo}/actions/cache/usage"
  | "GET /repos/{owner}/{repo}/actions/cache/usage-policy"
  | "GET /repos/{owner}/{repo}/actions/permissions/access"
  | "GET /repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}"
  | "GET /repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs"
  | "GET /repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/logs"
  | "GET /repos/{owner}/{repo}/codeowners/errors"
  | "GET /repos/{owner}/{repo}/tags/protection"
  | "PATCH /enterprises/{enterprise}/actions/cache/usage-policy"
  | "PATCH /repos/{owner}/{repo}/actions/cache/usage-policy"
  | "POST /repos/{owner}/{repo}/actions/jobs/{job_id}/rerun"
  | "POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs"
  | "POST /repos/{owner}/{repo}/tags/protection"
  | "PUT /orgs/{org}/actions/permissions/workflow"
  | "PUT /repos/{owner}/{repo}/actions/permissions/access";

declare module "@octokit-next/types" {
  namespace Octokit {
    interface ApiVersions {
      "ghes-3.4": {
        RequestHeaders: Octokit.ApiVersions["github.com"]["RequestHeaders"];

        ResponseHeaders: Simplify<
          Octokit.ApiVersions["ghes-3.5"]["ResponseHeaders"] &
            ResponseHeadersDiff
        >;

        Endpoints: Simplify<
          WithNewHeaders<
            Omit<
              Octokit.ApiVersions["ghes-3.5"]["Endpoints"],
              keyof AddedEndpoints | RemovedRoutes
            > &
              AddedEndpoints,
            Octokit.ApiVersions["ghes-3.4"]["ResponseHeaders"]
          >
        >;
      };
    }
  }
}
